AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  FrontEndBucketName:
    Type: String
    Default: compressed-website-bucket
    Description: The name for your s3 bucket that will host your website's files (static content)

Resources:
  FrontEndFilesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref FrontEndBucketName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: FrontEndFilesBucketPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref FrontEndFilesBucket
                - /*
      Bucket: !Ref FrontEndFilesBucket
Outputs:
  WebsiteURL:
    Value: !GetAtt
      - FrontEndFilesBucket
      - WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join
      - ''
      - - 'https://'
        - !GetAtt
          - FrontEndFilesBucket
          - DomainName
    Description: URL/Name of S3 bucket to hold website content
